### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by austinveteto** [austinveteto/spitfire#8]

**Comment by Austin-V** [comment]
favicon.ico 404 (Not Found) is an error that occurs when visiting the site

**Comment by Austin-V** [comment]
SVG vs SVGZ (gzip compressed)

**Comment by Austin-V** [comment]
https://jakearchibald.github.io/svgomg/

**Comment by austinveteto** [comment]
solved with https://github.com/austinveteto/spitfire/pull/28
